"""Initial migration

Revision ID: 7a216572a792
Revises: 
Create Date: 2025-05-16 21:12:24.894547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a216572a792'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhooks', sa.Column('webhook_url', sa.String(), nullable=False))
    op.add_column('webhooks', sa.Column('hashed_webhook_secret', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhooks', 'hashed_webhook_secret')
    op.drop_column('webhooks', 'webhook_url')
    # ### end Alembic commands ###
