"""installation id in repo_config

Revision ID: cb160bd59741
Revises: 1598a2c6ab14
Create Date: 2025-05-22 13:36:29.656981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb160bd59741'
down_revision: Union[str, None] = '1598a2c6ab14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configs', sa.Column('installation_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configs', 'installation_id')
    # ### end Alembic commands ###
