"""Use non-native enum for GitHostPlatform

Revision ID: efdd7634257c
Revises: ae5e284bb2a0
Create Date: 2025-05-29 21:26:54.504692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efdd7634257c'
down_revision: Union[str, None] = 'ae5e284bb2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('configs', 'platform',
               existing_type=postgresql.ENUM('GITHUB', 'GITLAB', 'BITBUCKET', 'GENERIC', name='githostplatform'),
               type_=sa.Enum('github', 'gitlab', 'bitbucket', 'generic', name='githostplatform', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('configs', 'platform',
               existing_type=sa.Enum('github', 'gitlab', 'bitbucket', 'generic', name='githostplatform', native_enum=False),
               type_=postgresql.ENUM('GITHUB', 'GITLAB', 'BITBUCKET', 'GENERIC', name='githostplatform'),
               existing_nullable=False)
    # ### end Alembic commands ###
